/* Tyranids — fan-sourced stat lines from Wahapedia 11th CSV (2026-08-27).
   Not official. Purple in the editor. Points still from MFM seed.
   Do not treat as accepted until checked against the app or a card. */
PTSheetsPack("tyranids-pts", {
  faction: "Tyranids",
  sheets: {
    "barbed-hierodule": {
      id: "barbed-hierodule",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Barbed Hierodule",
      keywords: ["MONSTER", "BARBED HIERODULE", "GREAT DEVOURER", "FRAME"],
      search: ["barbed hierodule", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 12, Sv: 2, Inv: 0, W: 18, Ld: 8, OC: 5, baseMm: 127,
      composition: { label: "1 Barbed Hierodule", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Bio-cannon", kind: "ranged", range: "48\"", A: "D6+3", BS: "3", S: 9, AP: "-2", D: "2", tags: ["BLAST"] }, { name: "Hierodule scything talons", kind: "melee", range: "Melee", A: "8", WS: "3", S: 14, AP: "-2", D: "D3+3", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "overgrown-barbs", name: "Overgrown Barbs", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Barbed-Hierodule" }
    },
    "barbgaunts": {
      id: "barbgaunts",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Barbgaunts",
      keywords: ["INFANTRY", "GREAT DEVOURER", "BARBGAUNTS"],
      search: ["barbgaunts", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 4, Sv: 4, Inv: 0, W: 2, Ld: 8, OC: 1, baseMm: 40,
      composition: { label: "5-10 Barbgaunts", defaultCount: 5 },
      pts: 55, ptsProposed: 55, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 5, pts: 55, tier: "unit" }, { count: 10, pts: 110, tier: "unit" }],
      weapons: [{ name: "Barblauncher", kind: "ranged", range: "24\"", A: "D6", BS: "4", S: 5, AP: "0", D: "1", tags: ["BLAST", "HEAVY"] }, { name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "1", WS: "4", S: 4, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "synapse", name: "Synapse", pending: true }, { id: "disruption-bombardment", name: "Disruption Bombardment", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Barbgaunts" }
    },
    "biovores": {
      id: "biovores",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Biovores",
      keywords: ["GREAT DEVOURER", "INFANTRY", "BIOVORES"],
      search: ["biovores", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 5, T: 6, Sv: 3, Inv: 0, W: 5, Ld: 8, OC: 1, baseMm: 80,
      composition: { label: "1-3 Biovores", defaultCount: 1 },
      pts: 60, ptsProposed: 60, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 60, tier: "unit" }, { count: 2, pts: 100, tier: "unit" }, { count: 3, pts: 140, tier: "unit" }],
      weapons: [{ name: "Spore Mine launcher", kind: "ranged", range: "48\"", A: "D3", BS: "4", S: 6, AP: "-1", D: "2", tags: ["BLAST", "DEVASTATING WOUNDS", "HEAVY", "INDIRECT FIRE"] }, { name: "Chitin-barbed limbs", kind: "melee", range: "Melee", A: "2", WS: "4", S: 5, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "seed-spore-mines", name: "Seed Spore Mines", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Biovores" }
    },
    "broodlord": {
      id: "broodlord",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Broodlord",
      keywords: ["PSYKER", "CHARACTER", "INFANTRY", "SYNAPSE", "VANGUARD INVADER", "BROODLORD", "GREAT DEVOURER"],
      search: ["broodlord", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 5, Sv: 4, Inv: 4, W: 6, Ld: 7, OC: 1, baseMm: 75,
      composition: { label: "1 Broodlord", defaultCount: 1 },
      pts: 80, ptsProposed: 80, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 80, tier: "unit" }],
      weapons: [{ name: "Broodlord claws and talons", kind: "melee", range: "Melee", A: "5", WS: "2", S: 6, AP: "-2", D: "2", tags: ["DEVASTATING WOUNDS", "TWIN-LINKED"] }],
      abilities: [{ id: "leader", name: "Leader", pending: true }, { id: "scouts", name: "Scouts", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "vicious-insight", name: "Vicious Insight", pending: true }, { id: "hypnotic-gaze", name: "Hypnotic Gaze (Psychic)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Broodlord" }
    },
    "carnifexes": {
      id: "carnifexes",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Carnifexes",
      keywords: ["CARNIFEXES", "GREAT DEVOURER", "MONSTER"],
      search: ["carnifexes", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 9, Sv: 2, Inv: 0, W: 8, Ld: 8, OC: 3, baseMm: 105,
      composition: { label: "1-2 Carnifexes", defaultCount: 1 },
      pts: 90, ptsProposed: 90, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 90, tier: "unit" }, { count: 2, pts: 180, tier: "unit" }],
      weapons: [{ name: "Bio-plasma", kind: "ranged", range: "12\"", A: "D3", BS: "4", S: 7, AP: "-2", D: "1", tags: ["ASSAULT", "BLAST"] }, { name: "Deathspitters with slimer maggots", kind: "ranged", range: "24\"", A: "6", BS: "4", S: 7, AP: "-2", D: "1", tags: [] }, { name: "Devourers with brainleech worms", kind: "ranged", range: "18\"", A: "12", BS: "4", S: 6, AP: "0", D: "1", tags: [] }, { name: "Heavy venom cannon", kind: "ranged", range: "36\"", A: "D3", BS: "4", S: 9, AP: "-2", D: "3", tags: ["BLAST"] }, { name: "Spine banks", kind: "ranged", range: "6\"", A: "5", BS: "4", S: 5, AP: "0", D: "1", tags: ["ASSAULT"] }, { name: "Stranglethorn cannon", kind: "ranged", range: "36\"", A: "D6+1", BS: "4", S: 7, AP: "-1", D: "2", tags: ["BLAST"] }, { name: "Carnifex crushing claws", kind: "melee", range: "Melee", A: "4", WS: "4", S: 12, AP: "-3", D: "D6+1", tags: [] }, { name: "Carnifex extra scything talons", kind: "melee", range: "Melee", A: "2", WS: "4", S: 9, AP: "-2", D: "3", tags: ["EXTRA ATTACKS"] }, { name: "Carnifex scything talons", kind: "melee", range: "Melee", A: "6", WS: "4", S: 9, AP: "-2", D: "3", tags: [] }, { name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "4", WS: "4", S: 6, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "blistering-assault", name: "Blistering Assault", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Carnifexes" }
    },
    "deathleaper": {
      id: "deathleaper",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Deathleaper",
      keywords: ["DEATHLEAPER", "INFANTRY", "CHARACTER", "EPIC HERO", "GREAT DEVOURER", "VANGUARD INVADER"],
      search: ["deathleaper", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 6, Sv: 3, Inv: 4, W: 7, Ld: 7, OC: 1, baseMm: 60,
      composition: { label: "1 Deathleaper – <span class=\"kwb\">EPIC</span> <span class=\"kwb\">HERO</span>", defaultCount: 1 },
      pts: 80, ptsProposed: 80, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 80, tier: "unit" }],
      weapons: [{ name: "Lictor claws and talons", kind: "melee", range: "Melee", A: "6", WS: "2", S: 7, AP: "-2", D: "2", tags: ["PRECISION"] }],
      abilities: [{ id: "fights-first", name: "Fights First", pending: true }, { id: "infiltrators", name: "Infiltrators", pending: true }, { id: "lone-operative", name: "Lone Operative", pending: true }, { id: "stealth", name: "Stealth", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "feeder-tendrils", name: "Feeder Tendrils", pending: true }, { id: "fear-of-the-unseen", name: "Fear of the Unseen (Aura)", pending: true }, { id: "hunter-organism", name: "HUNTER ORGANISM", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Deathleaper" }
    },
    "dimachaeron": {
      id: "dimachaeron",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Dimachaeron",
      keywords: ["DIMACHAERON", "GREAT DEVOURER", "MONSTER", "FRAME"],
      search: ["dimachaeron", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 10, Sv: 3, Inv: 5, W: 16, Ld: 7, OC: 5, baseMm: 120,
      composition: { label: "1 Dimachaeron", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Massive scything sickle-talons", kind: "melee", range: "Melee", A: "10", WS: "3", S: 9, AP: "-2", D: "3", tags: ["TWIN-LINKED"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "digestion-spine", name: "Digestion Spine", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Dimachaeron" }
    },
    "exocrine": {
      id: "exocrine",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Exocrine",
      keywords: ["MONSTER", "EXOCRINE", "GREAT DEVOURER"],
      search: ["exocrine", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 10, Sv: 3, Inv: 0, W: 14, Ld: 8, OC: 4, baseMm: 120,
      composition: { label: "1 Exocrine", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Bio-plasmic cannon", kind: "ranged", range: "36\"", A: "D6+3", BS: "3", S: 9, AP: "-3", D: "3", tags: ["BLAST", "HEAVY"] }, { name: "Powerful limbs", kind: "melee", range: "Melee", A: "3", WS: "3", S: 7, AP: "0", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "symbiotic-targeting", name: "Symbiotic Targeting", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Exocrine" }
    },
    "gargoyles": {
      id: "gargoyles",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Gargoyles",
      keywords: ["GARGOYLES", "ENDLESS MULTITUDE", "GREAT DEVOURER", "FLY", "BATTLELINE", "INFANTRY", "VANGUARD INVADER"],
      search: ["gargoyles", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 3, Sv: 6, Inv: 0, W: 1, Ld: 8, OC: 2, baseMm: 32,
      composition: { label: "10-20 Gargoyles", defaultCount: 10 },
      pts: 80, ptsProposed: 80, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 10, pts: 80, tier: "unit" }, { count: 20, pts: 155, tier: "unit" }],
      weapons: [{ name: "Fleshborer", kind: "ranged", range: "18\"", A: "1", BS: "4", S: 5, AP: "0", D: "1", tags: ["ASSAULT"] }, { name: "Blinding venom", kind: "melee", range: "Melee", A: "1", WS: "4", S: 3, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "winged-swarm", name: "Winged Swarm", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Gargoyles" }
    },
    "genestealers": {
      id: "genestealers",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Genestealers",
      keywords: ["INFANTRY", "VANGUARD INVADER", "GENESTEALERS", "GREAT DEVOURER"],
      search: ["genestealers", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 4, Sv: 5, Inv: 5, W: 2, Ld: 7, OC: 1, baseMm: 32,
      composition: { label: "5-10 Genestealers", defaultCount: 5 },
      pts: 75, ptsProposed: 75, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 5, pts: 75, tier: "1st-2nd" }, { count: 10, pts: 140, tier: "1st-2nd" }, { count: 5, pts: 85, tier: "3rd+" }, { count: 10, pts: 150, tier: "3rd+" }],
      weapons: [{ name: "Genestealer claws and talons", kind: "melee", range: "Melee", A: "4", WS: "2", S: 4, AP: "-2", D: "1", tags: [] }],
      abilities: [{ id: "scouts", name: "Scouts", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "vanguard-predator", name: "Vanguard Predator", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Genestealers" }
    },
    "harpy": {
      id: "harpy",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Harpy",
      keywords: ["FLY", "GREAT DEVOURER", "AIRCRAFT", "MONSTER", "HARPY", "VANGUARD INVADER"],
      search: ["harpy", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 0, T: 9, Sv: 3, Inv: 0, W: 12, Ld: 8, OC: 0, baseMm: 120,
      composition: { label: "1 Harpy", defaultCount: 1 },
      pts: 185, ptsProposed: 185, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 185, tier: "unit" }],
      weapons: [{ name: "Stinger salvoes", kind: "ranged", range: "24\"", A: "8", BS: "3", S: 5, AP: "0", D: "1", tags: [] }, { name: "Twin heavy venom cannon", kind: "ranged", range: "36\"", A: "D3", BS: "3", S: 9, AP: "-2", D: "3", tags: ["BLAST", "TWIN-LINKED"] }, { name: "Twin stranglethorn cannon", kind: "ranged", range: "36\"", A: "D6+1", BS: "2", S: 7, AP: "-1", D: "2", tags: ["BLAST", "TWIN-LINKED"] }, { name: "Scything wings", kind: "melee", range: "Melee", A: "4", WS: "4", S: 7, AP: "-1", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "hover", name: "Hover", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "spore-mine-cysts", name: "Spore Mine Cysts", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Harpy" }
    },
    "haruspex": {
      id: "haruspex",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Haruspex",
      keywords: ["MONSTER", "GREAT DEVOURER", "HARVESTER", "HARUSPEX"],
      search: ["haruspex", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 11, Sv: 3, Inv: 0, W: 14, Ld: 8, OC: 4, baseMm: 120,
      composition: { label: "1 Haruspex", defaultCount: 1 },
      pts: 125, ptsProposed: 125, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 125, tier: "1st-2nd" }, { count: 1, pts: 135, tier: "3rd+" }],
      weapons: [{ name: "Grasping tongue", kind: "ranged", range: "12\"", A: "1", BS: "3", S: 6, AP: "-2", D: "D6+1", tags: ["PRECISION"] }, { name: "Ravenous maw", kind: "melee", range: "Melee", A: "14", WS: "3", S: 7, AP: "-1", D: "2", tags: [] }, { name: "Shovelling claws", kind: "melee", range: "Melee", A: "4", WS: "3", S: 14, AP: "-2", D: "D6+1", tags: ["EXTRA ATTACKS"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "grisly-spectacle", name: "Grisly Spectacle", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Haruspex" }
    },
    "hive-crone": {
      id: "hive-crone",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Hive Crone",
      keywords: ["HIVE CRONE", "VANGUARD INVADER", "GREAT DEVOURER", "AIRCRAFT", "MONSTER", "FLY"],
      search: ["hive crone", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 0, T: 9, Sv: 3, Inv: 0, W: 12, Ld: 8, OC: 0, baseMm: 120,
      composition: { label: "1 Hive Crone", defaultCount: 1 },
      pts: 170, ptsProposed: 170, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 170, tier: "unit" }],
      weapons: [{ name: "Drool cannon", kind: "ranged", range: "12\"", A: "2D6", BS: "N/A", S: 6, AP: "-1", D: "1", tags: ["TORRENT"] }, { name: "Stinger salvoes", kind: "ranged", range: "24\"", A: "8", BS: "3", S: 5, AP: "0", D: "1", tags: [] }, { name: "Tentaclids", kind: "ranged", range: "36\"", A: "4", BS: "3", S: 7, AP: "0", D: "2", tags: ["ANTI-VEHICLE 4+", "DEVASTATING WOUNDS"] }, { name: "Scything wings", kind: "melee", range: "Melee", A: "4", WS: "4", S: 7, AP: "-1", D: "2", tags: [] }, { name: "Thorax spur", kind: "melee", range: "Melee", A: "1", WS: "3", S: 10, AP: "-3", D: "D6", tags: ["ANTI-FLY 2+", "EXTRA ATTACKS"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "airborne-predator", name: "Airborne Predator", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Hive-Crone" }
    },
    "hive-guard": {
      id: "hive-guard",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Hive Guard",
      keywords: ["GREAT DEVOURER", "INFANTRY", "HIVE GUARD"],
      search: ["hive guard", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 7, Sv: 3, Inv: 0, W: 4, Ld: 8, OC: 1, baseMm: 50,
      composition: { label: "3-6 Hive Guard", defaultCount: 3 },
      pts: 80, ptsProposed: 80, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 80, tier: "1st-2nd" }, { count: 6, pts: 160, tier: "1st-2nd" }, { count: 3, pts: 90, tier: "3rd+" }, { count: 6, pts: 170, tier: "3rd+" }],
      weapons: [{ name: "Impaler cannon", kind: "ranged", range: "36\"", A: "4", BS: "4", S: 5, AP: "-1", D: "1", tags: ["HEAVY", "INDIRECT FIRE"] }, { name: "Shockcannon", kind: "ranged", range: "24\"", A: "2", BS: "3", S: 7, AP: "-1", D: "3", tags: ["ANTI-VEHICLE 2+"] }, { name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "3", WS: "4", S: 5, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "synapse", name: "Synapse", pending: true }, { id: "defensive-stance", name: "Defensive Stance", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Hive-Guard" }
    },
    "hive-tyrant": {
      id: "hive-tyrant",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Hive Tyrant",
      keywords: ["HIVE TYRANT", "PSYKER", "MONSTER", "GREAT DEVOURER", "SYNAPSE", "CHARACTER"],
      search: ["hive tyrant", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 10, Sv: 2, Inv: 4, W: 10, Ld: 7, OC: 3, baseMm: 60,
      composition: { label: "1 Hive Tyrant", defaultCount: 1 },
      pts: 195, ptsProposed: 195, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 195, tier: "unit" }],
      weapons: [{ name: "Heavy venom cannon", kind: "ranged", range: "36\"", A: "D3", BS: "2", S: 9, AP: "-2", D: "3", tags: ["BLAST"] }, { name: "Stranglethorn cannon", kind: "ranged", range: "36\"", A: "D6+1", BS: "2", S: 7, AP: "-1", D: "2", tags: ["BLAST"] }, { name: "Monstrous bonesword and lash whip", kind: "melee", range: "Melee", A: "6", WS: "2", S: 9, AP: "-2", D: "3", tags: ["TWIN-LINKED"] }, { name: "Monstrous scything talons", kind: "melee", range: "Melee", A: "4", WS: "2", S: 7, AP: "-2", D: "2", tags: ["EXTRA ATTACKS"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "leader", name: "Leader", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "will-of-the-hive-mind", name: "Will of the Hive Mind", pending: true }, { id: "onslaught", name: "Onslaught (Aura, Psychic)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Hive-Tyrant" }
    },
    "hormagaunts": {
      id: "hormagaunts",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Hormagaunts",
      keywords: ["HORMAGAUNTS", "INFANTRY", "BATTLELINE", "GREAT DEVOURER", "ENDLESS MULTITUDE"],
      search: ["hormagaunts", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 10, T: 3, Sv: 5, Inv: 0, W: 1, Ld: 8, OC: 2, baseMm: 28,
      composition: { label: "10-20 Hormagaunts", defaultCount: 10 },
      pts: 70, ptsProposed: 70, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 10, pts: 70, tier: "unit" }, { count: 20, pts: 120, tier: "unit" }],
      weapons: [{ name: "Hormagaunt talons", kind: "melee", range: "Melee", A: "3", WS: "4", S: 3, AP: "-1", D: "1", tags: [] }],
      abilities: [{ id: "synapse", name: "Synapse", pending: true }, { id: "bounding-leap", name: "Bounding Leap", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Hormagaunts" }
    },
    "lictor": {
      id: "lictor",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Lictor",
      keywords: ["GREAT DEVOURER", "INFANTRY", "VANGUARD INVADER", "LICTOR"],
      search: ["lictor", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 6, Sv: 4, Inv: 0, W: 6, Ld: 7, OC: 1, baseMm: 50,
      composition: { label: "1 Lictor", defaultCount: 1 },
      pts: 60, ptsProposed: 60, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 60, tier: "unit" }],
      weapons: [{ name: "Lictor claws and talons", kind: "melee", range: "Melee", A: "6", WS: "2", S: 7, AP: "-2", D: "2", tags: ["PRECISION"] }],
      abilities: [{ id: "fights-first", name: "Fights First", pending: true }, { id: "infiltrators", name: "Infiltrators", pending: true }, { id: "lone-operative", name: "Lone Operative", pending: true }, { id: "stealth", name: "Stealth", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "feeder-tendrils", name: "Feeder Tendrils", pending: true }, { id: "pheromone-trail", name: "Pheromone Trail", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Lictor" }
    },
    "malanthrope": {
      id: "malanthrope",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Malanthrope",
      keywords: ["CHARACTER", "MALANTHROPE", "INFANTRY", "FLY", "GREAT DEVOURER", "SYNAPSE"],
      search: ["malanthrope", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 5, Sv: 4, Inv: 0, W: 10, Ld: 7, OC: 3, baseMm: 60,
      composition: { label: "1 Malanthrope", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Grasping tail", kind: "melee", range: "Melee", A: "4", WS: "4", S: 5, AP: "0", D: "2", tags: [] }],
      abilities: [{ id: "leader", name: "Leader", pending: true }, { id: "stealth", name: "Stealth", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "enhanced-toxic-miasma", name: "Enhanced Toxic Miasma", pending: true }, { id: "prey-adaptation", name: "Prey Adaptation", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Malanthrope" }
    },
    "maleceptor": {
      id: "maleceptor",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Maleceptor",
      keywords: ["SYNAPSE", "MALECEPTOR", "GREAT DEVOURER", "PSYKER", "MONSTER"],
      search: ["maleceptor", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 11, Sv: 3, Inv: 4, W: 14, Ld: 7, OC: 4, baseMm: 120,
      composition: { label: "1 Maleceptor", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Psychic overload", kind: "ranged", range: "18\"", A: "D6+3", BS: "3", S: 10, AP: "-2", D: "3", tags: ["BLAST", "PSYCHIC"] }, { name: "Massive scything talons – strike", kind: "melee", range: "Melee", A: "3", WS: "3", S: 9, AP: "-2", D: "D6+1", tags: [] }, { name: "Massive scything talons – sweep", kind: "melee", range: "Melee", A: "6", WS: "3", S: 7, AP: "-1", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "encephalic-diffusion", name: "Encephalic Diffusion (Aura, Psychic)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Maleceptor" }
    },
    "mawloc": {
      id: "mawloc",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Mawloc",
      keywords: ["BURROWER", "GREAT DEVOURER", "MONSTER", "MAWLOC", "VANGUARD INVADER"],
      search: ["mawloc", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 10, T: 10, Sv: 3, Inv: 0, W: 14, Ld: 8, OC: 4, baseMm: 120,
      composition: { label: "1 Mawloc", defaultCount: 1 },
      pts: 135, ptsProposed: 135, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 135, tier: "unit" }],
      weapons: [{ name: "Distensible jaw", kind: "melee", range: "Melee", A: "1", WS: "3", S: 5, AP: "0", D: "3", tags: ["ANTI-INFANTRY 4+", "DEVASTATING WOUNDS", "EXTRA ATTACKS"] }, { name: "Mawloc scything talons", kind: "melee", range: "Melee", A: "16", WS: "3", S: 8, AP: "-2", D: "1", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "terror-from-the-deep", name: "Terror From The Deep", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Mawloc" }
    },
    "mucolid-spores": {
      id: "mucolid-spores",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Beast",
      name: "Mucolid Spores",
      keywords: ["MUCOLID SPORES", "FLY", "GREAT DEVOURER", "BEAST"],
      search: ["mucolid spores", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 4, T: 4, Sv: 7, Inv: 0, W: 3, Ld: 8, OC: 0, baseMm: 40,
      composition: { label: "1-2 Mucolid Spores", defaultCount: 1 },
      pts: 30, ptsProposed: 30, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 30, tier: "unit" }, { count: 2, pts: 60, tier: "unit" }],
      weapons: [{ name: "Weapon", kind: "melee", range: "Melee", A: "0", WS: "-", S: 0, AP: "0", D: "-", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "bio-minefield", name: "Bio-minefield", pending: true }, { id: "floating-death", name: "Floating Death", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Mucolid-Spores" }
    },
    "neurogaunts": {
      id: "neurogaunts",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Neurogaunts",
      keywords: ["INFANTRY", "NEUROGAUNTS", "ENDLESS MULTITUDE", "GREAT DEVOURER"],
      search: ["neurogaunts", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 3, Sv: 6, Inv: 0, W: 1, Ld: 8, OC: 1, baseMm: 25,
      composition: { label: "1-2 Neurogaunt Nodebeasts*; 10-20 Neurogaunts", defaultCount: 1 },
      pts: 45, ptsProposed: 45, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 11, pts: 45, tier: "unit" }, { count: 22, pts: 90, tier: "unit" }],
      weapons: [{ name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "1", WS: "4", S: 3, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "synapse", name: "Synapse", pending: true }, { id: "neurocytes", name: "Neurocytes", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Neurogaunts" }
    },
    "neurolictor": {
      id: "neurolictor",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Neurolictor",
      keywords: ["INFANTRY", "VANGUARD INVADER", "NEUROLICTOR", "SYNAPSE", "GREAT DEVOURER"],
      search: ["neurolictor", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 5, Sv: 4, Inv: 4, W: 7, Ld: 7, OC: 1, baseMm: 50,
      composition: { label: "1 Neurolictor", defaultCount: 1 },
      pts: 80, ptsProposed: 80, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 80, tier: "1st-2nd" }, { count: 1, pts: 90, tier: "3rd+" }],
      weapons: [{ name: "Piercing claws and talons", kind: "melee", range: "Melee", A: "6", WS: "2", S: 6, AP: "-2", D: "1", tags: ["PRECISION"] }],
      abilities: [{ id: "infiltrators", name: "Infiltrators", pending: true }, { id: "lone-operative", name: "Lone Operative", pending: true }, { id: "stealth", name: "Stealth", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "feeder-tendrils", name: "Feeder Tendrils", pending: true }, { id: "neural-disruption", name: "Neural Disruption", pending: true }, { id: "psychological-saboteur", name: "Psychological Saboteur (Aura)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Neurolictor" }
    },
    "neurotyrant": {
      id: "neurotyrant",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Neurotyrant",
      keywords: ["CHARACTER", "SYNAPSE", "MONSTER", "NEUROTYRANT", "GREAT DEVOURER", "PSYKER", "FLY"],
      search: ["neurotyrant", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 8, Sv: 4, Inv: 4, W: 9, Ld: 7, OC: 3, baseMm: 50,
      composition: { label: "1 Neurotyrant", defaultCount: 1 },
      pts: 130, ptsProposed: 130, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 130, tier: "unit" }],
      weapons: [{ name: "Psychic scream", kind: "ranged", range: "18\"", A: "2D6", BS: "N/A", S: 5, AP: "-1", D: "2", tags: ["IGNORES COVER", "PSYCHIC", "TORRENT"] }, { name: "Neurotyrant claws and lashes", kind: "melee", range: "Melee", A: "6", WS: "3", S: 5, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "leader", name: "Leader", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "node-lash", name: "Node Lash (Psychic)", pending: true }, { id: "psychic-terror", name: "Psychic Terror (Psychic)", pending: true }, { id: "neuroloids", name: "Neuroloids", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Neurotyrant" }
    },
    "norn-assimilator": {
      id: "norn-assimilator",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Norn Assimilator",
      keywords: ["SYNAPSE", "HARVESTER", "NORN ASSIMILATOR", "MONSTER", "GREAT DEVOURER"],
      search: ["norn assimilator", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 10, T: 11, Sv: 2, Inv: 0, W: 16, Ld: 7, OC: 5, baseMm: 100,
      composition: { label: "1 Norn Assimilator", defaultCount: 1 },
      pts: 250, ptsProposed: 250, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 250, tier: "1st" }, { count: 1, pts: 270, tier: "2nd+" }],
      weapons: [{ name: "Toxinjector Harpoon", kind: "ranged", range: "12\"", A: "2", BS: "2", S: 12, AP: "-3", D: "D6+1", tags: ["HARPOONED"] }, { name: "Monstrous scything talons", kind: "melee", range: "Melee", A: "6", WS: "2", S: 9, AP: "-2", D: "3", tags: [] }, { name: "Toxinjector harpoon", kind: "melee", range: "Melee", A: "4", WS: "2", S: 12, AP: "-3", D: "D6+1", tags: ["EXTRA ATTACKS"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "singular-purpose", name: "Singular Purpose", pending: true }, { id: "harpoon-barbs", name: "Harpoon Barbs", pending: true }, { id: "harpooned", name: "Harpooned", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Norn-Assimilator" }
    },
    "norn-emissary": {
      id: "norn-emissary",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Norn Emissary",
      keywords: ["NORN EMISSARY", "MONSTER", "PSYKER", "GREAT DEVOURER", "SYNAPSE"],
      search: ["norn emissary", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 10, T: 11, Sv: 2, Inv: 4, W: 16, Ld: 7, OC: 5, baseMm: 100,
      composition: { label: "1 Norn Emissary", defaultCount: 1 },
      pts: 250, ptsProposed: 250, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 250, tier: "1st" }, { count: 1, pts: 270, tier: "2nd+" }],
      weapons: [{ name: "Psychic Tendril – neuroparasite", kind: "ranged", range: "18\"", A: "2", BS: "2", S: 8, AP: "-2", D: "D3", tags: ["PRECISION", "PSYCHIC"] }, { name: "Psychic Tendril – neuroblast", kind: "ranged", range: "18\"", A: "2D6", BS: "2", S: 6, AP: "-2", D: "1", tags: ["BLAST", "PSYCHIC"] }, { name: "Psychic Tendril – neurolance", kind: "ranged", range: "18\"", A: "2", BS: "2", S: 12, AP: "-3", D: "D6", tags: ["MELTA 2", "PSYCHIC"] }, { name: "Monstrous scything talons", kind: "melee", range: "Melee", A: "6", WS: "2", S: 9, AP: "-2", D: "3", tags: [] }, { name: "Monstrous rending claws", kind: "melee", range: "Melee", A: "4", WS: "2", S: 7, AP: "-2", D: "2", tags: ["EXTRA ATTACKS"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "singular-purpose", name: "Singular Purpose", pending: true }, { id: "unnatural-resilience", name: "Unnatural Resilience", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Norn-Emissary" }
    },
    "old-one-eye": {
      id: "old-one-eye",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Old One Eye",
      keywords: ["MONSTER", "EPIC HERO", "OLD ONE EYE", "GREAT DEVOURER", "CHARACTER"],
      search: ["old one eye", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 9, Sv: 2, Inv: 0, W: 9, Ld: 8, OC: 3, baseMm: 105,
      composition: { label: "1 Old One Eye – <span class=\"kwb\">EPIC</span> <span class=\"kwb\">HERO</span>", defaultCount: 1 },
      pts: 140, ptsProposed: 140, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 140, tier: "unit" }],
      weapons: [{ name: "Old One Eye’s claws and talons – strike", kind: "melee", range: "Melee", A: "6", WS: "3", S: 14, AP: "-3", D: "D6+1", tags: [] }, { name: "Old One Eye’s claws and talons – sweep", kind: "melee", range: "Melee", A: "12", WS: "3", S: 6, AP: "-1", D: "1", tags: [] }],
      abilities: [{ id: "feel-no-pain", name: "Feel No Pain", pending: true }, { id: "leader", name: "Leader", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "alpha-leader", name: "Alpha Leader", pending: true }, { id: "unstoppable-monster", name: "Unstoppable Monster", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Old-One-Eye" }
    },
    "parasite-of-mortrex": {
      id: "parasite-of-mortrex",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Parasite Of Mortrex",
      keywords: ["PARASITE OF MORTREX", "INFANTRY", "CHARACTER", "FLY", "SYNAPSE", "VANGUARD INVADER", "GREAT DEVOURER"],
      search: ["parasite of mortrex", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 5, Sv: 4, Inv: 0, W: 5, Ld: 8, OC: 1, baseMm: 40,
      composition: { label: "1 Parasite of Mortrex", defaultCount: 1 },
      pts: 70, ptsProposed: 70, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 70, tier: "unit" }],
      weapons: [{ name: "Barbed ovipositor", kind: "melee", range: "Melee", A: "1", WS: "2", S: 3, AP: "-2", D: "3", tags: ["ANTI-INFANTRY 3+", "EXTRA ATTACKS"] }, { name: "Clawed limbs", kind: "melee", range: "Melee", A: "6", WS: "2", S: 5, AP: "-1", D: "1", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "lone-operative", name: "Lone Operative", pending: true }, { id: "stealth", name: "Stealth", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "parasitic-infection", name: "Parasitic Infection", pending: true }, { id: "it-itches", name: "It Itches!", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Parasite-Of-Mortrex" }
    },
    "psychophage": {
      id: "psychophage",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Psychophage",
      keywords: ["PSYCHOPHAGE", "SMOKE", "HARVESTER", "GREAT DEVOURER", "MONSTER"],
      search: ["psychophage", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 9, Sv: 3, Inv: 0, W: 10, Ld: 8, OC: 3, baseMm: 120,
      composition: { label: "1 Psychophage", defaultCount: 1 },
      pts: 110, ptsProposed: 110, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 110, tier: "unit" }],
      weapons: [{ name: "Psychoclastic torrent", kind: "ranged", range: "12\"", A: "D6", BS: "N/A", S: 6, AP: "-1", D: "1", tags: ["IGNORES COVER", "TORRENT"] }, { name: "Talons and betentacled maw", kind: "melee", range: "Melee", A: "6", WS: "3", S: 6, AP: "-2", D: "2", tags: ["ANTI-PSYKER 4+", "DEVASTATING WOUNDS"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "feel-no-pain", name: "Feel No Pain", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "bio-stimulus", name: "Bio-stimulus", pending: true }, { id: "feeding-frenzy", name: "Feeding Frenzy", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Psychophage" }
    },
    "pyrovores": {
      id: "pyrovores",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Pyrovores",
      keywords: ["INFANTRY", "GREAT DEVOURER", "HARVESTER", "PYROVORES"],
      search: ["pyrovores", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 5, T: 6, Sv: 3, Inv: 0, W: 5, Ld: 8, OC: 1, baseMm: 80,
      composition: { label: "1-3 Pyrovores", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Flamespurt", kind: "ranged", range: "12\"", A: "D6+1", BS: "N/A", S: 6, AP: "-1", D: "1", tags: ["IGNORES COVER", "TORRENT", "TWIN-LINKED"] }, { name: "Chitin-barbed limbs", kind: "melee", range: "Melee", A: "2", WS: "4", S: 5, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "burning-spray", name: "Burning Spray", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Pyrovores" }
    },
    "ripper-swarms": {
      id: "ripper-swarms",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Swarm",
      name: "Ripper Swarms",
      keywords: ["GREAT DEVOURER", "SWARM", "RIPPER SWARMS", "HARVESTER"],
      search: ["ripper swarms", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 2, Sv: 6, Inv: 0, W: 4, Ld: 8, OC: 0, baseMm: 40,
      composition: { label: "1-3 Ripper Swarms", defaultCount: 1 },
      pts: 30, ptsProposed: 30, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 30, tier: "unit" }, { count: 2, pts: 40, tier: "unit" }, { count: 3, pts: 50, tier: "unit" }],
      weapons: [{ name: "Spinemaws", kind: "ranged", range: "6\"", A: "4", BS: "5", S: 3, AP: "0", D: "1", tags: ["PISTOL"] }, { name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "6", WS: "5", S: 2, AP: "0", D: "1", tags: ["SUSTAINED HITS 1"] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "chitinous-horrors", name: "Chitinous Horrors (Aura)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Ripper-Swarms" }
    },
    "screamer-killer": {
      id: "screamer-killer",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Screamer-killer",
      keywords: ["MONSTER", "GREAT DEVOURER", "SCREAMER-KILLER"],
      search: ["screamer-killer", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 9, Sv: 2, Inv: 0, W: 10, Ld: 8, OC: 3, baseMm: 90,
      composition: { label: "1 Screamer-Killer", defaultCount: 1 },
      pts: 125, ptsProposed: 125, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 125, tier: "1st-2nd" }, { count: 1, pts: 135, tier: "3rd+" }],
      weapons: [{ name: "Bio-plasmic scream", kind: "ranged", range: "18\"", A: "D6+3", BS: "4", S: 8, AP: "-2", D: "1", tags: ["ASSAULT", "BLAST"] }, { name: "Screamer-killer talons", kind: "melee", range: "Melee", A: "10", WS: "3", S: 10, AP: "-2", D: "3", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "death-scream", name: "Death Scream", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Screamer-killer" }
    },
    "scythed-hierodule": {
      id: "scythed-hierodule",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Scythed Hierodule",
      keywords: ["FRAME", "GREAT DEVOURER", "SCYTHED HIERODULE", "MONSTER"],
      search: ["scythed hierodule", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 12, Sv: 2, Inv: 0, W: 18, Ld: 8, OC: 5, baseMm: 127,
      composition: { label: "1 Scythed Hierodule", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Bio-acid spray", kind: "ranged", range: "18\"", A: "3D6", BS: "N/A", S: 6, AP: "-2", D: "1", tags: ["TORRENT"] }, { name: "Hierodule scything talons", kind: "melee", range: "Melee", A: "10", WS: "3", S: 14, AP: "-2", D: "D3+3", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "irresistible-force", name: "Irresistible Force", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Scythed-Hierodule" }
    },
    "sky-slasher-swarms": {
      id: "sky-slasher-swarms",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Swarm",
      name: "Sky-slasher Swarms",
      keywords: ["FLY", "SKY-SLASHER SWARMS", "GREAT DEVOURER", "SWARM"],
      search: ["sky-slasher swarms", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 2, Sv: 6, Inv: 0, W: 4, Ld: 8, OC: 0, baseMm: 40,
      composition: { label: "3 Sky-slasher Swarms", defaultCount: 3 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 0, tier: "unit" }],
      weapons: [{ name: "Spinemaws", kind: "ranged", range: "6\"", A: "4", BS: "5", S: 3, AP: "0", D: "1", tags: ["PISTOL"] }, { name: "Claws and teeth", kind: "melee", range: "Melee", A: "6", WS: "5", S: 2, AP: "0", D: "1", tags: ["SUSTAINED HITS 1"] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "chitinous-horrors", name: "Chitinous Horrors", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Sky-slasher-Swarms" }
    },
    "spore-mines": {
      id: "spore-mines",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Beast",
      name: "Spore Mines",
      keywords: ["BEAST", "SPORE MINES", "GREAT DEVOURER", "FLY"],
      search: ["spore mines", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 4, T: 1, Sv: 7, Inv: 0, W: 1, Ld: 8, OC: 0, baseMm: 25,
      composition: { label: "3-6 Spore Mines", defaultCount: 3 },
      pts: 55, ptsProposed: 55, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 55, tier: "unit" }, { count: 6, pts: 110, tier: "unit" }],
      weapons: [{ name: "Weapon", kind: "melee", range: "Melee", A: "0", WS: "-", S: 0, AP: "0", D: "-", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "bio-minefield", name: "Bio-minefield", pending: true }, { id: "floating-death", name: "Floating Death", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Spore-Mines" }
    },
    "sporocyst": {
      id: "sporocyst",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Sporocyst",
      keywords: ["SPOROCYST", "MONSTER", "GREAT DEVOURER"],
      search: ["sporocyst", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 0, T: 10, Sv: 3, Inv: 0, W: 10, Ld: 8, OC: 0, baseMm: 100,
      composition: { label: "1 Sporocyst", defaultCount: 1 },
      pts: 145, ptsProposed: 145, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 145, tier: "unit" }],
      weapons: [{ name: "Sporocyst bio-weapons", kind: "ranged", range: "24\"", A: "10", BS: "4", S: 5, AP: "-1", D: "2", tags: [] }, { name: "Flensing whips", kind: "melee", range: "Melee", A: "6", WS: "4", S: 7, AP: "-1", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "seed-mucolids", name: "Seed Mucolids", pending: true }, { id: "hive-defences", name: "Hive Defences", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Sporocyst" }
    },
    "swarmlord": {
      id: "swarmlord",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "The Swarmlord",
      keywords: ["EPIC HERO", "SYNAPSE", "GREAT DEVOURER", "PSYKER", "CHARACTER", "MONSTER", "HIVE TYRANT", "THE SWARMLORD"],
      search: ["the swarmlord", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 10, Sv: 2, Inv: 4, W: 10, Ld: 7, OC: 3, baseMm: 60,
      composition: { label: "1 Swarmlord – <span class=\"kwb\">EPIC</span> <span class=\"kwb\">HERO</span>", defaultCount: 1 },
      pts: 210, ptsProposed: 210, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 210, tier: "unit" }],
      weapons: [{ name: "Synaptic pulse", kind: "ranged", range: "18\"", A: "D6+3", BS: "N/A", S: 5, AP: "-1", D: "2", tags: ["PSYCHIC", "TORRENT"] }, { name: "Bone sabres", kind: "melee", range: "Melee", A: "8", WS: "2", S: 9, AP: "-2", D: "3", tags: ["TWIN-LINKED"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "leader", name: "Leader", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "hive-commander", name: "Hive Commander", pending: true }, { id: "malign-presence", name: "Malign Presence (Aura)", pending: true }, { id: "domination-of-the-hive-mind", name: "Domination of the Hive Mind (Aura)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/The-Swarmlord" }
    },
    "termagants": {
      id: "termagants",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Termagants",
      keywords: ["INFANTRY", "TERMAGANTS", "ENDLESS MULTITUDE", "GREAT DEVOURER", "BATTLELINE"],
      search: ["termagants", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 3, Sv: 5, Inv: 0, W: 1, Ld: 8, OC: 2, baseMm: 28,
      composition: { label: "10-20 Termagants", defaultCount: 10 },
      pts: 60, ptsProposed: 60, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 10, pts: 60, tier: "unit" }, { count: 20, pts: 110, tier: "unit" }],
      weapons: [{ name: "Fleshborer", kind: "ranged", range: "18\"", A: "1", BS: "4", S: 5, AP: "0", D: "1", tags: ["ASSAULT"] }, { name: "Shardlauncher", kind: "ranged", range: "18\"", A: "D3", BS: "4", S: 5, AP: "0", D: "1", tags: ["BLAST", "HEAVY"] }, { name: "Spike rifle", kind: "ranged", range: "24\"", A: "1", BS: "4", S: 4, AP: "-1", D: "1", tags: ["HEAVY"] }, { name: "Strangleweb", kind: "ranged", range: "18\"", A: "D6", BS: "N/A", S: 2, AP: "0", D: "1", tags: ["ASSAULT", "DEVASTATING WOUNDS", "TORRENT"] }, { name: "Termagant devourer", kind: "ranged", range: "18\"", A: "2", BS: "4", S: 4, AP: "0", D: "1", tags: [] }, { name: "Termagant spinefists", kind: "ranged", range: "12\"", A: "2", BS: "4", S: 3, AP: "0", D: "1", tags: ["ASSAULT", "PISTOL", "TWIN-LINKED"] }, { name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "1", WS: "4", S: 3, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "synapse", name: "Synapse", pending: true }, { id: "skulking-horrors", name: "Skulking Horrors", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Termagants" }
    },
    "tervigon": {
      id: "tervigon",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Tervigon",
      keywords: ["TERVIGON", "GREAT DEVOURER", "SYNAPSE", "MONSTER", "CHARACTER", "PSYKER"],
      search: ["tervigon", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 11, Sv: 2, Inv: 0, W: 16, Ld: 7, OC: 5, baseMm: 120,
      composition: { label: "1 Tervigon", defaultCount: 1 },
      pts: 160, ptsProposed: 160, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 160, tier: "unit" }],
      weapons: [{ name: "Stinger salvoes", kind: "ranged", range: "24\"", A: "8", BS: "3", S: 5, AP: "0", D: "1", tags: [] }, { name: "Massive crushing claws", kind: "melee", range: "Melee", A: "4", WS: "4", S: 12, AP: "-3", D: "D6+1", tags: [] }, { name: "Massive scything talons – strike", kind: "melee", range: "Melee", A: "4", WS: "3", S: 9, AP: "-2", D: "D6", tags: [] }, { name: "Massive scything talons – sweep", kind: "melee", range: "Melee", A: "8", WS: "3", S: 7, AP: "-1", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "spawn-termagants", name: "Spawn Termagants", pending: true }, { id: "brood-progenitor", name: "Brood Progenitor (Aura, Psychic)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Tervigon" }
    },
    "toxicrene": {
      id: "toxicrene",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Toxicrene",
      keywords: ["TOXICRENE", "FRAME", "GREAT DEVOURER", "MONSTER"],
      search: ["toxicrene", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 11, Sv: 3, Inv: 0, W: 14, Ld: 8, OC: 4, baseMm: 120,
      composition: { label: "1 Toxicrene", defaultCount: 1 },
      pts: 120, ptsProposed: 120, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 120, tier: "unit" }],
      weapons: [{ name: "Massive toxic lashes", kind: "ranged", range: "9\"", A: "2D6", BS: "3", S: 6, AP: "-1", D: "2", tags: ["ANTI-INFANTRY 2+"] }, { name: "Massive toxic lashes", kind: "melee", range: "Melee", A: "12", WS: "3", S: 6, AP: "-1", D: "2", tags: ["ANTI-INFANTRY 2+"] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "grasping-tendrils", name: "Grasping Tendrils", pending: true }, { id: "hypertoxic-miasma", name: "Hypertoxic Miasma (Aura)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Toxicrene" }
    },
    "trygon": {
      id: "trygon",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Trygon",
      keywords: ["BURROWER", "VANGUARD INVADER", "GREAT DEVOURER", "TRYGON", "MONSTER"],
      search: ["trygon", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 10, T: 10, Sv: 3, Inv: 0, W: 14, Ld: 8, OC: 4, baseMm: 120,
      composition: { label: "1 Trygon", defaultCount: 1 },
      pts: 140, ptsProposed: 140, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 140, tier: "unit" }],
      weapons: [{ name: "Bio-electric pulse", kind: "ranged", range: "12\"", A: "6", BS: "3", S: 5, AP: "0", D: "1", tags: ["SUSTAINED HITS 2"] }, { name: "Trygon scything talons", kind: "melee", range: "Melee", A: "12", WS: "3", S: 9, AP: "-2", D: "3", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "subterranean-tunnels", name: "Subterranean Tunnels", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Trygon" }
    },
    "tyranid-warriors-with-melee-bio-weapons": {
      id: "tyranid-warriors-with-melee-bio-weapons",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Tyranid Warriors With Melee Bio-weapons",
      keywords: ["GREAT DEVOURER", "INFANTRY", "SYNAPSE", "TYRANID WARRIORS WITH MELEE BIO-WEAPONS"],
      search: ["tyranid warriors with melee bio-weapons", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 5, Sv: 4, Inv: 0, W: 3, Ld: 7, OC: 2, baseMm: 50,
      composition: { label: "1 Tyranid Prime; 2-5 Tyranid Warriors", defaultCount: 2 },
      pts: 75, ptsProposed: 75, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 75, tier: "unit" }, { count: 6, pts: 150, tier: "unit" }],
      weapons: [{ name: "Tyranid Warrior claws and talons", kind: "melee", range: "Melee", A: "6", WS: "3", S: 5, AP: "-2", D: "1", tags: ["TWIN-LINKED"] }],
      abilities: [{ id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "adaptive-instincts", name: "Adaptive Instincts (Once per turn, per unit)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Tyranid-Warriors-With-Melee-Bio-weapons" }
    },
    "tyranid-warriors-with-ranged-bio-weapons": {
      id: "tyranid-warriors-with-ranged-bio-weapons",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Tyranid Warriors With Ranged Bio-weapons",
      keywords: ["SYNAPSE", "INFANTRY", "GREAT DEVOURER", "TYRANID WARRIORS WITH RANGED BIO-WEAPONS"],
      search: ["tyranid warriors with ranged bio-weapons", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 5, Sv: 4, Inv: 0, W: 3, Ld: 7, OC: 2, baseMm: 50,
      composition: { label: "1 Tyranid Prime; 2-5 Tyranid Warriors", defaultCount: 2 },
      pts: 60, ptsProposed: 60, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 60, tier: "unit" }, { count: 6, pts: 120, tier: "unit" }],
      weapons: [{ name: "Barbed strangler", kind: "ranged", range: "36\"", A: "D6+1", BS: "4", S: 6, AP: "-1", D: "1", tags: ["BLAST"] }, { name: "Deathspitter", kind: "ranged", range: "24\"", A: "3", BS: "4", S: 5, AP: "-1", D: "1", tags: [] }, { name: "Devourer", kind: "ranged", range: "18\"", A: "5", BS: "4", S: 4, AP: "0", D: "1", tags: [] }, { name: "Spinefists", kind: "ranged", range: "12\"", A: "2", BS: "4", S: 4, AP: "0", D: "1", tags: ["ASSAULT", "PISTOL", "TWIN-LINKED"] }, { name: "Venom cannon", kind: "ranged", range: "36\"", A: "D3", BS: "4", S: 9, AP: "-2", D: "2", tags: ["BLAST"] }, { name: "Tyranid Warrior claws and talons", kind: "melee", range: "Melee", A: "5", WS: "3", S: 5, AP: "-1", D: "1", tags: [] }],
      abilities: [{ id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "adaptable-predators", name: "Adaptable Predators", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Tyranid-Warriors-With-Ranged-Bio-weapons" }
    },
    "tyrannocyte": {
      id: "tyrannocyte",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Tyrannocyte",
      keywords: ["GREAT DEVOURER", "TRANSPORT", "MONSTER", "DEDICATED TRANSPORT", "VANGUARD INVADER", "FLY", "TYRANNOCYTE", "FRAME"],
      search: ["tyrannocyte", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 8, T: 9, Sv: 3, Inv: 0, W: 10, Ld: 8, OC: 2, baseMm: 100,
      composition: { label: "1 Tyrannocyte", defaultCount: 1 },
      pts: 80, ptsProposed: 80, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 80, tier: "1st-3rd" }, { count: 1, pts: 90, tier: "4th+" }],
      weapons: [{ name: "Tyrannocyte bio-weapons", kind: "ranged", range: "24\"", A: "5", BS: "4", S: 5, AP: "-1", D: "2", tags: [] }, { name: "Flensing whips", kind: "melee", range: "Melee", A: "6", WS: "4", S: 7, AP: "-1", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "deep-strike", name: "Deep Strike", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "aerial-seeding", name: "Aerial Seeding", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Tyrannocyte" }
    },
    "tyrannofex": {
      id: "tyrannofex",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Tyrannofex",
      keywords: ["TYRANNOFEX", "FRAME", "GREAT DEVOURER", "MONSTER"],
      search: ["tyrannofex", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 9, T: 12, Sv: 2, Inv: 0, W: 16, Ld: 8, OC: 5, baseMm: 120,
      composition: { label: "1 Tyrannofex", defaultCount: 1 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 0, tier: "unit" }],
      weapons: [{ name: "Acid spray", kind: "ranged", range: "18\"", A: "D6+6", BS: "N/A", S: 6, AP: "-2", D: "2", tags: ["TORRENT"] }, { name: "Fleshborer hive", kind: "ranged", range: "24\"", A: "20", BS: "3", S: 5, AP: "0", D: "1", tags: ["HEAVY", "SUSTAINED HITS 1", "TWIN-LINKED"] }, { name: "Rupture cannon", kind: "ranged", range: "48\"", A: "2", BS: "3", S: 18, AP: "-4", D: "D6+6", tags: ["HEAVY"] }, { name: "Stinger salvoes", kind: "ranged", range: "24\"", A: "8", BS: "3", S: 5, AP: "0", D: "1", tags: [] }, { name: "Powerful limbs", kind: "melee", range: "Melee", A: "4", WS: "3", S: 8, AP: "0", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "resilient-organism", name: "Resilient Organism", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Tyrannofex" }
    },
    "tyrant-guard": {
      id: "tyrant-guard",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Tyrant Guard",
      keywords: ["INFANTRY", "TYRANT GUARD", "GREAT DEVOURER"],
      search: ["tyrant guard", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 8, Sv: 3, Inv: 0, W: 4, Ld: 8, OC: 1, baseMm: 50,
      composition: { label: "3-6 Tyrant Guard", defaultCount: 3 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 0, tier: "unit" }],
      weapons: [{ name: "Bone cleaver, lash whip and rending claws", kind: "melee", range: "Melee", A: "3", WS: "3", S: 5, AP: "-1", D: "2", tags: [] }, { name: "Crushing claws and rending claws", kind: "melee", range: "Melee", A: "2", WS: "4", S: 8, AP: "-2", D: "2", tags: ["TWIN-LINKED"] }, { name: "Scything talons and rending claws", kind: "melee", range: "Melee", A: "5", WS: "3", S: 5, AP: "-1", D: "1", tags: [] }],
      abilities: [{ id: "synapse", name: "Synapse", pending: true }, { id: "guardian-organism", name: "Guardian Organism", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Tyrant-Guard" }
    },
    "venomthropes": {
      id: "venomthropes",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Venomthropes",
      keywords: ["VENOMTHROPES", "FLY", "GREAT DEVOURER", "INFANTRY"],
      search: ["venomthropes", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 6, T: 5, Sv: 4, Inv: 0, W: 3, Ld: 8, OC: 1, baseMm: 40,
      composition: { label: "3-6 Venomthropes", defaultCount: 3 },
      pts: 55, ptsProposed: 55, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 55, tier: "unit" }, { count: 6, pts: 110, tier: "unit" }],
      weapons: [{ name: "Toxic lashes", kind: "melee", range: "Melee", A: "5", WS: "3", S: 3, AP: "0", D: "1", tags: ["ANTI-INFANTRY 2+"] }],
      abilities: [{ id: "stealth", name: "Stealth", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "foul-spores", name: "Foul Spores (Aura)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Venomthropes" }
    },
    "von-ryans-leapers": {
      id: "von-ryans-leapers",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Von Ryan’s Leapers",
      keywords: ["GREAT DEVOURER", "VON RYAN\u2019S LEAPERS", "VANGUARD INVADER", "INFANTRY"],
      search: ["von ryan\u2019s leapers", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 10, T: 5, Sv: 4, Inv: 6, W: 3, Ld: 8, OC: 1, baseMm: 40,
      composition: { label: "3-6 Von Ryan’s Leapers", defaultCount: 3 },
      pts: 55, ptsProposed: 55, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 3, pts: 55, tier: "unit" }, { count: 6, pts: 105, tier: "unit" }],
      weapons: [{ name: "Leaper’s talons", kind: "melee", range: "Melee", A: "6", WS: "3", S: 5, AP: "-1", D: "1", tags: [] }],
      abilities: [{ id: "fights-first", name: "Fights First", pending: true }, { id: "infiltrators", name: "Infiltrators", pending: true }, { id: "stealth", name: "Stealth", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "pouncing-leap", name: "Pouncing Leap", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Von-Ryan-s-Leapers" }
    },
    "winged-hive-tyrant": {
      id: "winged-hive-tyrant",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Monster",
      name: "Winged Hive Tyrant",
      keywords: ["WINGED HIVE TYRANT", "HIVE TYRANT", "MONSTER", "FLY", "GREAT DEVOURER", "SYNAPSE", "PSYKER", "VANGUARD INVADER", "CHARACTER"],
      search: ["winged hive tyrant", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 9, Sv: 2, Inv: 4, W: 10, Ld: 7, OC: 3, baseMm: 60,
      composition: { label: "1 Winged Hive Tyrant", defaultCount: 1 },
      pts: 185, ptsProposed: 185, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 185, tier: "unit" }],
      weapons: [{ name: "Heavy venom cannon", kind: "ranged", range: "36\"", A: "D3", BS: "2", S: 9, AP: "-2", D: "3", tags: ["BLAST"] }, { name: "Stranglethorn cannon", kind: "ranged", range: "36\"", A: "D6+1", BS: "2", S: 7, AP: "-1", D: "2", tags: ["BLAST"] }, { name: "Monstrous bonesword and lash whip", kind: "melee", range: "Melee", A: "6", WS: "2", S: 9, AP: "-2", D: "3", tags: ["TWIN-LINKED"] }, { name: "Monstrous scything talons", kind: "melee", range: "Melee", A: "4", WS: "2", S: 7, AP: "-2", D: "2", tags: ["EXTRA ATTACKS"] }, { name: "Tyrant talons", kind: "melee", range: "Melee", A: "5", WS: "2", S: 7, AP: "-2", D: "2", tags: [] }],
      abilities: [{ id: "deadly-demise", name: "Deadly Demise", pending: true }, { id: "deep-strike", name: "Deep Strike", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "will-of-the-hive-mind", name: "Will of the Hive Mind", pending: true }, { id: "paroxysm", name: "Paroxysm (Psychic)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Winged-Hive-Tyrant" }
    },
    "winged-tyranid-prime": {
      id: "winged-tyranid-prime",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Winged Tyranid Prime",
      keywords: ["WINGED TYRANID PRIME", "SYNAPSE", "GREAT DEVOURER", "FLY", "CHARACTER", "INFANTRY", "VANGUARD INVADER"],
      search: ["winged tyranid prime", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 12, T: 5, Sv: 4, Inv: 0, W: 6, Ld: 7, OC: 1, baseMm: 50,
      composition: { label: "1 Winged Tyranid Prime", defaultCount: 1 },
      pts: 65, ptsProposed: 65, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 1, pts: 65, tier: "unit" }],
      weapons: [{ name: "Prime talons", kind: "melee", range: "Melee", A: "6", WS: "2", S: 6, AP: "-1", D: "2", tags: [] }],
      abilities: [{ id: "deep-strike", name: "Deep Strike", pending: true }, { id: "leader", name: "Leader", pending: true }, { id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "alpha-warrior", name: "Alpha Warrior", pending: true }, { id: "death-blow", name: "Death Blow", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Winged-Tyranid-Prime" }
    },
    "zoanthropes": {
      id: "zoanthropes",
      edition: "11th",
      faction: "Tyranids",
      factionKeywords: ["TYRANIDS"],
      type: "Infantry",
      name: "Zoanthropes",
      keywords: ["SYNAPSE", "GREAT DEVOURER", "FLY", "PSYKER", "INFANTRY", "ZOANTHROPES"],
      search: ["zoanthropes", "tyranids", "fan"],
      fanSourced: true,
      sheetComplete: false,
      pendingStats: false,
      M: 5, T: 5, Sv: 5, Inv: 4, W: 3, Ld: 7, OC: 1, baseMm: 40,
      composition: { label: "1 Neurothrope; 2-5 Zoanthropes", defaultCount: 2 },
      pts: 0, ptsProposed: 0, ptsSource: "proposed", ptsMfmVersion: "1.3",
      ptsBands: [{ count: 2, pts: 0, tier: "unit" }],
      weapons: [{ name: "Warp Blast – witchfire", kind: "ranged", range: "24\"", A: "D3", BS: "3", S: 7, AP: "-2", D: "D3", tags: ["BLAST", "PSYCHIC"] }, { name: "Warp Blast – focused witchfire", kind: "ranged", range: "24\"", A: "1", BS: "3", S: 12, AP: "-3", D: "D6+1", tags: ["LETHAL HITS", "PSYCHIC"] }, { name: "Chitinous claws and teeth", kind: "melee", range: "Melee", A: "2", WS: "5", S: 3, AP: "0", D: "1", tags: [] }],
      abilities: [{ id: "shadow-in-the-warp", name: "Shadow in the Warp", pending: true }, { id: "synapse", name: "Synapse", pending: true }, { id: "spirit-leech", name: "Spirit Leech (Aura, Psychic)", pending: true }, { id: "warp-field", name: "Warp Field (Aura, Psychic)", pending: true }],
      source: { kind: "fan", label: "Wahapedia 11th (unofficial)", file: "", page: "", hub: "https://wahapedia.ru/wh40k11ed/factions/tyranids/Zoanthropes" }
    }
  }
});
